apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-admin
spec:
  selector:
    matchLabels:
      app: powerdns-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: powerdns-admin
    spec:
      containers:
        - name: powerdns-admin
          image: ngoduykhanh/powerdns-admin:latest@sha256:780054dc22136be4ec53e7bf26331717e45b49e4828969d9ab872d60a10c2bcb
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: postgresql://ns001:12345ABCDEF4242@postgresql.pgsql.svc.cluster.local/ns001
            - name: BIND_ADDRESS
              value: "0.0.0.0:8000"
          securityContext:
            allowPrivilegeEscalation: false
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
      automountServiceAccountToken: false
