apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app: sonarr
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 5Gi
      