apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: syslog
      format: rfc3164
      timezone: Europe/Vienna
      protocol.udp:
        host: "0.0.0.0:9000"
    - type: mqtt
      hosts: 
        - tcp://mosquitto.mosquitto.svc.cluster.local:1883
      topics: 
        - "tele/+/SENSOR" # energy consumption data published by tasmota
      processors:
        - decode_json_fields:
            fields:
              - message
            process_array: false
            max_depth: 1
            target: ''
            overwrite_keys: false
            add_error_key: true
    filebeat.modules:
    - module: cisco
      meraki:
        enabled: true
        var.syslog_port: 9525
        var.input: udp
        var.syslog_host: 0.0.0.0
    output.elasticsearch:
      hosts: ["elasticsearch-master.elk.svc.cluster.local:9200"]
      username: '${ELASTICSEARCH_USERNAME:}'
      password: '${ELASTICSEARCH_PASSWORD:}'

kind: ConfigMap
metadata:
  name: filebeat-syslog
  namespace: elk
