apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filebeat-syslog
  name: filebeat-syslog
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat-syslog
  strategy: {}
  template:
    metadata:
      labels:
        app: filebeat-syslog
    spec:
      containers:
      - image: docker.elastic.co/beats/filebeat:8.5.2@sha256:717e57902aaf3b502d86287ea7875e740c62a6880a881e1156ed8f47e6f5bd86
        name: filebeat
        env:
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: password
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-cm
          readOnly: true
          subPath: filebeat.yml
      volumes:
        - name: filebeat-cm
          configMap:
            name: filebeat-syslog
            items:
            - key: "filebeat.yml"
              path: "filebeat.yml"

