apiVersion: v1
kind: Service
metadata:
  labels:
    app: filebeat-syslog
  name: filebeat-syslog
  namespace: elk
spec:
  ports:
  - port: 9525
    protocol: UDP
    targetPort: 9525
    name: UDP-Meraki
  - port: 9000
    protocol: UDP
    targetPort: 9000
    name: UDP-Synology
  selector:
    app: filebeat-syslog
  type: LoadBalancer
