apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: powerdns-api
spec:
  encryptedData:
    api.conf: AgBezaMapuJFk4V4YMZp09dcbY8fqOKLEV+Z4fFqNsgSP30TE2tC8UBQmffJs2HnvpypBUjMUoGX7nkRuQgOohKwrB+O9HeRIcxn/Dk4AQ48GRRG+hxaTFkN9Cehy+mOMy9PwkoNTUxLXVe21C7SGDpAZTuRBwsGdMXIiZkQshvRLpwy7qkaWc9F4FlPaHYLf2WusIW+blyFCLr9KUg8XX1J9U3mOZswXcmpe/anIubNkFcR7Y5FHZiylKcfleAoD2lrDJ/HAxK00y1z6e2DiT2kkOVPadGhSeUnBJamixb2h09X7Ln3OzA5sMXvRvEag9Jle9MmN6sZpn4wzu2gP+l1uATzV8NVgt/4b/vB8s7EpQdqPUFtxi7krIev/5FTOYsh5wHx2aUOx/rHoNKYRHYK+4SGMPv3S1NNeN7OK9/lOBxdnbdd0Rcx6Kx1WK3q411tTjdgSBhbibGmEJP9Tj2bKBbT+weGa6cVRCNi7UAZB/qVegIbuqBS5ODJHzKUnMuoF5KXVClgSwaklnJ/+NY7gH1QDtrJQkmI5i8p6lBpwEKUYmryXkk+/q5OSDTXgGROv2xBoYZuhNIaAsuWZsLz/mBo/u9cfs7+lLosc7zu6axPBzecModGNuFSxwlck1h/YxfAeGswM0/D/c842Xh6mwXm9LxMuc69xOY1P4d4tggPuRn4+r8KFqamE9TUMofo29HF7nBAQlMqBl8Il35OMYrVuG3gHQVuO9EgscqiLg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: powerdns-api
      namespace: powerdns
    type: Opaque

