apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-config
data:
  pdns.conf: |+
    # defense config
    daemon=no 
    default-ksk-algorithm=ed25519 
    default-ttl=1500 
    default-zsk-algorithm=ed25519 
    guardian=yes 
    include-dir=/etc/powerdns/conf.d
    local-address=0.0.0.0
    local-port=5353
    log-dns-queries=no
    loglevel=5
    version-string=anonymous

