apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-auth
spec:
  selector:
    matchLabels:
      app: powerdns
  replicas: 1
  template:
    metadata:
      labels:
        app: powerdns
    spec:
      containers:
        - name: powerdns-auth
          image: powerdns/pdns-auth-45:4.5.5@sha256:3ac13341b99132ab5321fe8ab71b6448e8d187dca4c74e6892d58ad9c5457243
          command:
            - "pdns_server"
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: powerdns-config
              mountPath: /etc/powerdns/pdns.conf
              subPath: pdns.conf
            - name: powerdns-db
              mountPath: /etc/powerdns/conf.d/db.conf
              subPath: db.conf
            - name: powerdns-webserver
              mountPath: /etc/powerdns/conf.d/webserver.conf
              subPath: webserver.conf
            - name: powerdns-api
              mountPath: /etc/powerdns/conf.d/api.conf
              subPath: api.conf
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: powerdns-config
          configMap:
            name: powerdns-config
        - name: powerdns-db
          secret:
            secretName: powerdns-db
        - name: powerdns-webserver
          secret:
            secretName: powerdns-webserver
        - name: powerdns-api
          secret:
            secretName: powerdns-api
