apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns001
spec:
  selector:
    matchLabels:
      app: powerdns
  replicas: 1
  template:
    metadata:
      labels:
        app: powerdns
    spec:
      containers:
        - name: ns001
          image: powerdns/pdns-auth-44:4.4.1
          command:
            - "pdns_server"
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: ns001
              mountPath: /etc/powerdns/pdns.conf
              subPath: pdns.conf
            - name: ns001
              mountPath: /etc/powerdns/conf.d/db.conf
              subPath: db.conf
            - name: ns001
              mountPath: /etc/powerdns/conf.d/webserver.conf
              subPath: webserver.conf
            - name: ns001
              mountPath: /etc/powerdns/conf.d/api.conf
              subPath: api.conf
            # - name: ns001-run
            #   mountPath: /var/run
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: ns001
          configMap:
            name: ns001
        - name: ns001-run
          emptyDir: {}
