apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
  name: powerdns-auth-http
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  type: LoadBalancer
  loadBalancerIP: "10.255.100.22"
  externalTrafficPolicy: Local
  selector:
    app: powerdns
