apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: dns
  name: powerdns-auth-tcp
spec:
  ports:
    - name: tcp-dns
      port: 53
      protocol: TCP
      targetPort: 5353
  type: LoadBalancer
  loadBalancerIP: "10.255.100.22"
  externalTrafficPolicy: Local
  selector:
    app: powerdns
