replicaCount: 2
image:
  # -- the repostory to pull the image from
  repository: "pihole/pihole"
  # -- the docker tag, if left empty it will get it from the chart's appVersion
  tag: "2023.10.0"
  # -- the pull policy
  pullPolicy: IfNotPresent
resources:
  limits:
      memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
DNS1: 208.67.222.222
DNS2: 208.67.220.220
persistentVolumeClaim:
  enabled: false
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
  - pihole.sauerwein.se
  tls:
  - hosts:
      - pihole.sauerwein.se
    secretName: pihole-cert
serviceDns:
  loadBalancerIP: 192.168.10.24
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 208.67.222.222
dnsmasq:
  customDnsEntries:
  - address=/pihole.sauerwein.se/192.168.10.10
  - address=/jackett.sauerwein.se/192.168.10.10
  - address=/sonarr.sauerwein.se/192.168.10.10
  - address=/radarr.sauerwein.se/192.168.10.10
extraEnvVars:
  QUERY_LOGGING: "false"
