replicaCount: 2
image:
  # -- the repostory to pull the image from
  repository: "pihole/pihole"
  # -- the docker tag, if left empty it will get it from the chart's appVersion
  tag: "2023.1@sha256:5d3f94aeaae60560d27310c5b234b711174de008f89a2a4c6f6110bd46a9f177"
  # -- the pull policy
  pullPolicy: IfNotPresent
resources:
  limits:
      memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
DNS1: 208.67.222.222
DNS2: 208.67.220.220
persistentVolumeClaim:
  enabled: false
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
  - pihole.sauerwein.se
  tls:
  - hosts:
      - pihole.sauerwein.se
    secretName: pihole-cert
serviceDns:
  loadBalancerIP: 10.255.100.24
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
  - 127.0.0.1
  - 208.67.222.222
dnsmasq:
  customDnsEntries:
  - address=/pihole.sauerwein.se/10.255.100.10
extraEnvVars:
  QUERY_LOGGING: "false"
