apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: radarr
  labels:
    app: radarr
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 5Gi
      