apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: kube-system
spec:
  encryptedData:
    speaker-secret: AgDhzCAct2I0MKByrx3Ws9plZpderK82nItA1S5/yM8DpjJ4ip+63n8VgcT33s9C4i2vbYHcYs3iC4Fqh65O5NOReF7Jz31CgXSOndqCtJai8Wg2E1d+yVEM/bSWg6WQGZXrk06Y2Uu+gUWUgyvzaqLwRspp7E6hWjuPIRkMyTmPMft6gfl4Qba+wqwURQnYg3x2lPqsUy0LNdOyJ5GOAaspta4fTNkCDhPxkam0tPJDHKjJEse+lDdAXlOTZWX4N5u1ZxHgOZkZVVw+AZTsrXrx32rVO7lxsnpf6C32RqI++DpXiVlJQouXwyu2oEctAkpLkHGpgPg2u1aCRGtYkSpxLzk3rjUlx1Xyhr5/tB3umLPLoYbQge0xReF4jE75GNqKjEO+RPPY4j9Jgk88WdyU97b6P2YZT3uiA8uc8uVYZ5fIfKZ/CeTKiPxAH39q+TIniirklyLSA4TsbKdb+ka64Rz4SgGpbe1AEZClGaTP02g2syMFsMlGDS0zcxkbJ31TsF+lzzFAffZ4HlmBqNKft7hUTJ456grfukQh8uiCrg85A6jkxQcXL1kEhqRC1cBKkUSTuC8rmo9VLmhYCElbjx59v5DII3iHMqdgUTvp8B7GBFhOCjcQYnaGwHD6vfo2Qe8QOTHzci8Y4V6NvhXawT1P8PM6a2ja16LbJC6AT024E/c+2Edt9+9ELGaUcj/07yp5+7VQYu/Q/0MIyT5ZYUwUtjSpBJXQ8HG0MWzDXSKypROUCHFmn1ylrsWmRvfXJbzDR7FbULPMrlIdp+4KLSMlM2iIby443lztEz82rsQAm6q27JyffZC4CQyGXBdcycWiJjTBTaJtdxruAtE/47OKuIOfGexIpZpSKP2TlziFZgtNiCh9oOn2i+cFfzc7tPUU+gNTnL9taFTVYDFmyeEkUzuYwuMMTIolo0j1Q/2Ohdkt6cc5DbxT7HDIplNOv1COwXRNGtEew+5LAdkWcJ6UvsqXXaa+TTiVscUfWtnNtb0JE05HL3OzcOmm3pC2MytYgoVyipyPsVc+lNSF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: kube-system

