apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: metallb-speaker-secret
  namespace: metallb
spec:
  encryptedData:
    speaker-secret: AgBIR4pRe4m+4IQI3hQE9xCT7gMYrGoFfhqnWIsA9oMb2k7zR0IH1j+CxVHj1e+eoMvQXihiVLEaUUPHq6ucCKl0iDWh/EtKankTAp9JgTGsEDzkMqED4BUB5IB/dhuTv+khnb2flnO6uMvh39Et6woOx5mlkhz8tuL7qoGoqTJTZCJ3CEqsMTUPbqi8vg5Ew2OfzWhrEiplk63uMgHhXO2aTXk2/Inl/GCbGHxbpew4l2nk1D3BqLLTzrIhDpEC1wGnnvquBG5nA7r6AWKkbSnrrmk2iqFbOH9TYE26pnh73uLb1Gt8icHEmMiHjJXO76dW3VZVqYTOGBfVmah+ebfTqj4pgtSIqyKb8DWgjQhvrvEmixQNuNu3LlsopKQedRiJonXgc0jUxHmdoAZLlOsUTDUpC+x7l/4dHs5nLn5otMfgA9JijMLbwwwTiyp3OFPARUUajYsQ3cZ/OxDt39IMkNugBNLfQkB8Fa0zyqD74zDTsb7NvFxt63vFuwShhQf0hP6uZ+qXIsk4tmZIkxcS1esEMVKv99ATSl1a6/tD8HWGPT4UiBwEhQ5aSSL6o5rGBpE+qIU0HvIHrUwOUt+ut4JoWu4kZGxMQxSMaaJie0fzR872w9eNlFa5J7SxPXcvBJ2B0ypdPuzUdJUgHMbkHYzrWw6aPXrs64PkBJQghYG1YSTUGUgb4sLj0UmqJtESEQ9hJJIwPXY2yrrmfHl7Xi/7FJKOnssLYlOLvguFHVPqmSlMBR0YkIf4Hll6LacWHLsVdj5NCgtqHnY2iz+tX56sQ70yxJSwZnABdGcvSDPXza7BkJ4ZURi7YkNYZGyngWZCLNZ1BToYk7IMItBRc3fJ/+V1B1HHAWcDb+08t80AsgVD/NVqZ/1jciYtkgpZsZ9EJqZyS9EoQ9e7VNghV6Ak1zS9hR1p6UT5FWJHpn+RW6iAi3G7mbByGDVIFDnNbvkRpHmUEGItRDE6YSIoyJnVlXOJ/UYgGkBMAj25a2OT+MRROr/BkCNbGO4XbgmzG+/zFEJayO7gPi0ItOX9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: metallb-speaker-secret
      namespace: metallb

