apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: splunk
  name: splunk
  namespace: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  strategy: {}
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - image: splunk/splunk:9.0.2@sha256:0be31e80a19326e83ff31f3b8d0b71c72f577b80157cf76cab4ab8cd64e7daa0
        name: splunk
        env:
        - name: SPLUNK_START_ARGS
          value: --accept-license
        # - name: SPLUNK_HTTP_ENABLESSL
        #   value: "true"
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk-credentials
              key: password
        - name: SPLUNK_LICENSE_URI
          value: /run/secrets/splunk_license
        volumeMounts:
        - mountPath: /opt/splunk/var
          name: data
        - mountPath: /opt/splunk/etc
          name: etc
        - name: license
          mountPath: /run/secrets/splunk_license
          subPath: splunk_license
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 8088
          name: hec
          protocol: TCP
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: splunk-data
      - name: etc
        persistentVolumeClaim:
          claimName: splunk-etc
      - name: license
        secret:
          secretName: splunk-license