apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: splunk
  name: splunk
  namespace: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  strategy: {}
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - image: splunk/splunk:8.2.6
        name: splunk
        env:
        - name: SPLUNK_START_ARGS
          value: --accept-license
        # - name: SPLUNK_HTTP_ENABLESSL
        #   value: "true"
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk-credentials
              key: password
        volumeMounts:
        - mountPath: /opt/splunk/var
          name: data
        - mountPath: /opt/splunk/etc
          name: etc
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 8088
          name: hec
          protocol: TCP
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: splunk-data
      - name: etc
        persistentVolumeClaim:
          claimName: splunk-etc
