apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett
  namespace: jackett
  labels:
    app: jackett
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 5Gi
      