apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thousandeyes-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs-client
