apiVersion: v1
data:
  rsyslog.conf: |-
    # Provides UDP syslog reception
    $ModLoad imudp
    $UDPServerRun 514
    action(type="omfile" dirCreateMode="0700" FileCreateMode="0644" File="/log/meraki.log")
  droprules.conf: ""
  container_config: |-
    # rsyslog syslog appliance container configuration.
    # This file will be sourced upon container startup.
    # Uncomment those settings that you need and set them to your
    # desired values.

    # general container app settings:
    export TZ=UTC
    #export CONTAINER_SILENT=on  # do not emit startup message
    export ENABLE_STATISTICS=on
kind: ConfigMap
metadata:
  name: rsyslog

