apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: rsyslog
    app.kubernetes.io/name: rsyslog
  name: rsyslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: rsyslog
      app.kubernetes.io/name: rsyslog
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: rsyslog
        app.kubernetes.io/name: rsyslog
    spec:
      containers:
      - image: rsyslog/syslog_appliance_alpine@sha256:c0dd7cad9ff3234967ff59879590175b7590e8a5f5621ec49a85aff546b44a3b
        name: syslog
        env:
        - name: RSYSLOG_CONF
          value: /config/rsyslog.conf
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /work
          name: work
        - mountPath: /log
          name: log
      - image: telegraf:1.24.4@sha256:8710dcedf791862ac377a8f1f2c18dd4dc0a07d96b0cb14cd32359786036d3a3
        name: telegraf
        volumeMounts:
        - mountPath: /log
          name: log
        - mountPath: /etc/telegraf
          name: telegraf-syslog
      volumes:
        - name: config
          configMap:
            name: rsyslog
        - name: telegraf-syslog
          configMap:
            name: telegraf-syslog
        - name: work
          emptyDir: {}
        - name: log
          emptyDir: {}
