apiVersion: v1
data:
  telegraf.conf: |2

    [agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
       [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2


    [[outputs.influxdb_v2]]
      bucket = "telegraf/autogen"
      organization = "influxdata"
      token = "-bOzRPjgqsfVdkxFLP7oFMSlF6_ORSzpFp3k8j6eigBEY_F_XtKAQ1RbcofxqyUs3mbJro3gfH7Yjff6LLkfow=="
      urls = [
        "http://influxdb-influxdb2.influx.svc.cluster.local:8086"
      ]
    
    [[inputs.tail]]
    files = ["/log/meraki.log"]
    from_beginning = false
    data_format = "logfmt"
kind: ConfigMap
metadata:
  name: telegraf-syslog
  namespace: telegraf
