---
# Source: telegraf/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  labels:
    helm.sh/chart: telegraf-1.8.42
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: telegraf
data:
  telegraf.conf: |+
    
    [agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
       [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2
    
    
    [[outputs.influxdb_v2]]
      bucket = "telegraf/autogen"
      organization = "influxdata"
      token = "-bOzRPjgqsfVdkxFLP7oFMSlF6_ORSzpFp3k8j6eigBEY_F_XtKAQ1RbcofxqyUs3mbJro3gfH7Yjff6LLkfow=="
      urls = [
        "http://influxdb-influxdb2.influx.svc.cluster.local:8086"
      ]
    
    [[inputs.mqtt_consumer]]
      data_format = "json"
      servers = [
        "tcp://mosquitto.mosquitto.svc.cluster.local:1883"
      ]
      topics = [
        "tele/+/SENSOR"
      ]
    
    [[inputs.internal]]
      collect_memstats = false
---
# Source: telegraf/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
      app.kubernetes.io/instance: telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
        app.kubernetes.io/instance: telegraf
    spec:
      containers:
      - name: telegraf
        image: "telegraf:1.20-alpine"
        imagePullPolicy: "IfNotPresent"
        resources:
          {}
        env:
        - name: HOSTNAME
          value: telegraf-polling-service
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
      volumes:
      - name: config
        configMap:
          name: telegraf
