---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recursor-conf
data:
  recursor.conf: |
    local-address=0.0.0.0,::
    include-dir=/etc/powerdns/recursor.d
    local-port=5353
  forward-zones.conf: |
    forward-zones=sauerwein.se=10.255.100.22:53

