apiVersion: apps/v1
kind: Deployment
metadata:
  name: recursor
spec:
  selector:
    matchLabels:
      app: recursor
  replicas: 2
  template:
    metadata:
      labels:
        app: recursor
    spec:
      containers:
        - name: recursor
          image: powerdns/pdns-recursor-45:4.5.9@sha256:9dd493e6ba63e610fd930ab4cf78c43af8cd6c400c702efbb3b6c45d9cf93f18
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: recursor-conf
              mountPath: /etc/powerdns/recursor.conf
              subPath: recursor.conf
            - name: recursor-conf
              mountPath: /etc/powerdns/recursor.d/forward-zones.conf
              subPath: forward-zones.conf
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: recursor-conf
          configMap:
            name: recursor-conf

