apiVersion: apps/v1
kind: Deployment
metadata:
  name: recursor
spec:
  selector:
    matchLabels:
      app: recursor
  replicas: 2
  template:
    metadata:
      labels:
        app: recursor
    spec:
      containers:
        - name: recursor
          image: powerdns/pdns-recursor-45:4.5.11@sha256:527dbb5733833faa84baaeab250b7dbeb68c7ebdc7c2d6520b8ce0388b2ffe6f
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: recursor-conf
              mountPath: /etc/powerdns/recursor.conf
              subPath: recursor.conf
            - name: recursor-conf
              mountPath: /etc/powerdns/recursor.d/forward-zones.conf
              subPath: forward-zones.conf
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: recursor-conf
          configMap:
            name: recursor-conf

