apiVersion: apps/v1
kind: Deployment
metadata:
  name: recursor
spec:
  selector:
    matchLabels:
      app: recursor
  replicas: 2
  template:
    metadata:
      labels:
        app: recursor
    spec:
      containers:
        - name: recursor
          image: powerdns/pdns-recursor-45:4.5.12@sha256:2ab7d977c4f24b781c789c47fc60501b88451c240e418730b2b0c2b1e19a5d7d
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: recursor-conf
              mountPath: /etc/powerdns/recursor.conf
              subPath: recursor.conf
            - name: recursor-conf
              mountPath: /etc/powerdns/recursor.d/forward-zones.conf
              subPath: forward-zones.conf
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
        - name: recursor-conf
          configMap:
            name: recursor-conf

