---
# Source: telegraf/templates/pdb.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: RELEASE-NAME-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.38
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
      app.kubernetes.io/instance: RELEASE-NAME
---
# Source: telegraf/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.38
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: telegraf/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.38
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
data:
  telegraf.conf: |+
    
    [agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2
    
    
    [[outputs.influxdb]]
      database = "telegraf"
      urls = [
        "http://influxdb:8086"
      ]
    
    [[inputs.statsd]]
      allowed_pending_messages = 10000
      metric_separator = "_"
      percentile_limit = 1000
      percentiles = [
        50,
        95,
        99
      ]
      service_address = ":8125"
    [[inputs.mqtt_consumer]]
      data_format = "influx"
      password = "5QoschFUUghF44E"
      servers = [
        "tcp://10.255.20.108:1883"
      ]
      topics = [
        "tasmota"
      ]
      username = "DVES_USER"
    [[inputs.internal]]
      collect_memstats = false
---
# Source: telegraf/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: RELEASE-NAME-telegraf
  namespace: influx
  labels:
    helm.sh/chart: telegraf-1.7.38
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
rules:
  []
---
# Source: telegraf/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: RELEASE-NAME-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.38
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-telegraf
    namespace: influx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: RELEASE-NAME-telegraf
---
# Source: telegraf/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.38
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
spec:
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: 8125
    protocol: "UDP"
    name: "statsd"
  selector:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: telegraf/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-telegraf
  labels:
    helm.sh/chart: telegraf-1.7.38
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: RELEASE-NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        checksum/config: bb58e5996925c68bec40286bff36aa0be1e0171cb21611fe417f48c58ce6eea8
    spec:
      serviceAccountName: RELEASE-NAME-telegraf
      containers:
      - name: telegraf
        image: "telegraf:1.17-alpine"
        imagePullPolicy: "IfNotPresent"
        resources:
          {}
        env:
        - name: HOSTNAME
          value: telegraf-polling-service
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
      volumes:
      - name: config
        configMap:
          name: RELEASE-NAME-telegraf
